modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="aesthetic-nether"
version="0.1"
displayName="Aesthetic Nether"
updateJSONURL="https://raw.githubusercontent.com/Redstoneguy129/Aesthetic-Nether/master/Version.json"
authors=["Redstoneguy129", "EternalOne"]
description='''
Features from the Natura mod
'''
[[dependencies.aesthetic-nether]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aesthetic-nether]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"